
---
- name: Pull and Run docker image of milangupta16/calculator-devops
  hosts: all
  tasks:
    - name: Pull milangupta16/calculator-devops
      docker_image:
        name: milangupta16/calculator-devops
        source: pull
    - name: Create default containers
      docker_container:
        name: c1
        image: milangupta16/calculator-devops
        state: present
